### ISSUE TITLE
timer functionality

### ISSUE THREAD

**Issue by igors48** [igors48/timers#67]
```
0067-timer-functionality
#67 timer functionality
```

**Comment by igors48** [comment]
## idle
**background task**
do nothing
**next wake up**
don't care
## run
**background task**
decreases seconds counter
if the counter reaches zero - change the state to alarm
**next wake up**
according to the seconds counter
## pause
**background task**
do nothing
**next wake up**
don't care
## alarm
**background task**
if the alarm period is not finished - make a beep
if alarm period is finished - change state to idle
**next wake up**
no sleep

**Comment by igors48** [comment]
timer data
- `period`  
- `counter`
- `alarm duration`
- `alarm start`

timer api
- `start`
- `stop`
- `reset`
- `stopAlarm`
- `tick` - for background task

**Comment by igors48** [comment]
### if a branch will be just closed or will be merged
- [x] verify no uncommitted changes   
- [x] verify that all the needed tests are created (if the branch will be merged)  
- [x] verify that all the tests run by `RUN_TEST` (if the branch will be merged)  
- [x] verify that all the tests passed (if the branch will be merged)  
- [x] review issue notes, add them as the last comment    
- [x] review all commits notes, add them as the last comment    
- [x] review todos (if the branch will be just closed), add them as the last comment     
- [x] update the used [sources](https://github.com/igors48/timers/wiki/Links) 

### if the branch will be merged
- [x] update the documentation (checking the diff between `develop` and feature branches)
- [x] create missing or update existing doxygen   
- [x] clean up `#includes`   
- [x] verify no uncommitted changes    
- [x] switch to develop  
- [x] sync local develop with origin  
- [x] merge feature branch to develop  
- [x] build project for watch env  
- [x] run tests  
- [x] sync local develop with origin  
- [ ] verify that commits appear in develop origin     

### if a branch will be just closed or will be merged
- [x] delete the local feature branch  
- [x] delete the remote feature branch [here](https://github.com/igors48/timers/branches) 
- [x] review todos, create follow up issue(s)  
- [x] review the last comment, create follow up issue(s), add links to the issues        
- [x] close the related branch issue

**Comment by igors48** [comment]
- [x] `return timer.timeKeeper.duration; // todo replace two dots access with function` -> #81
- [x] `static unsigned int getSimulatedTickCount() // todo create time service with milliseconds simulation based on freertos ticks` -> #82
- [x] `// TODO create factory method for app tiles creation` -> #80
- [x] `unsigned int secondsToNextWakeUp = (p->manager->getNextWakeUpPeriod)() / 1000; // todo fix it by decision what it should be - secs or millis` -> #82
- [x] `system suspend and resume // todo seems not needed anymore` -> #79 
- [x] `timerAppTickerParameters = { // todo create factory method for that` -> #78
